version: '3.8'

services:
  db:
    image: postgres:16
    container_name: renal_db
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: renal_app
#    restart: always
#    environment:
#      - DB_HOST=$DB_HOST
#      - DB_PORT=$DB_PORT
#      - DB_NAME=$DB_NAME
#      - DB_USER=$DB_USER
#      - DB_PASSWORD=$DB_PASSWORD
#    depends_on:
#      - db
#    ports:
#      - "8000:8000"
#    command: [ "bash", "-c", "python db/create_db.py && python db/main.py" ]

volumes:
  pg_data: